### ISSUE TITLE
Failure to Open Repository Project in Bolt

### ISSUE THREAD

**Issue by engmsilva** [Labhk/BoltSync-Issues#1]
I was able to execute all the steps:

- App Install
- Upload the zip file to the repository

However, when opening the project in Bolt, a permission error occurs.

In the GitHub settings, boltsync has all the permissions.

![image](https://github.com/user-attachments/assets/2de24a62-2ed2-45f7-8ab3-204a2a930b26)

![image](https://github.com/user-attachments/assets/fd50c77d-a34d-465f-9a7a-ee1266d50beb)

**Comment by Labhk** [comment]
Bro If your repo is private then you can't open it in Bolt, Bolt only have feature to import public repos, plz check if ur repo is private, also boltsync github permissions and bolt.new are not related they are two seperate websites

**Comment by engmsilva** [comment]
Changing the repository to public solved the problem, I thought that having a paid account would be possible to use a private repository. 

So every time I change the project in Bolt I need to download the project and import it again through boltsync?

**Comment by Labhk** [comment]
yeh thats the steps to keep your github repo updated.

**Comment by Labhk** [comment]
I'll close this issue

**Comment by engmsilva** [comment]
You can close this issue. Thanks for your help.
