### ISSUE TITLE
 I'm stuck on this problem

### ISSUE THREAD

**Issue by engmsilva** [Labhk/BoltSync-Issues#2]
I've been stuck on this screen for some time, nothing happens

![image](https://github.com/user-attachments/assets/a026f48b-c3cc-4963-adf5-ee26453647ab)

**Comment by Labhk** [comment]
Hi, Is your zip too large?
Only thing I suggest is to reload the app and try again.
if after retry if it still persist let me know

**Comment by engmsilva** [comment]
Now I'm stuck at this stage, more than 2800 requests have already been made. The zip file is 41MB

![image](https://github.com/user-attachments/assets/c2f6eb73-b3bd-4154-858f-4fa242cd3a2b)

**Comment by Labhk** [comment]
41mb is big, that may be that problem 
Also how many file have u modified, these are too many I think that's why it got stuck, I'll check it out. see if this can be fixed

**Comment by engmsilva** [comment]
There was a bug when generating the zip file on the Bolt. Bolt was adding the node_modules directory It seems the bug has been resolved as I re-downloaded the 68k zip file and now it works without error.

**Comment by Labhk** [comment]
Alright, Beware of node_modules folder it can crash anything with its size😂
