### ISSUE TITLE
Cannot Import Repo into Bolt

### ISSUE THREAD

**Issue by pomasco** [Labhk/BoltSync-Issues#4]
I have recently experienced that I cannot import one of my repositories. I have checked all settings and have tried all possible solutions to fix this issue:

- I have logged out then logged back in again
- Uninstalled then reinstalled the GitHub app
- Selected the single repository instead of all repositories

The repository in question is https://github.com/pomasco/leads.soletraderai

**Comment by Labhk** [comment]
try renaming your repo to leads-soletraderai or something

**Comment by pomasco** [comment]
> try renaming your repo to leads-soletraderai or something

Great! This approach worked! Thank you so much

**Comment by pomasco** [comment]
This has been resolved
