### ISSUE TITLE
It looks like boltsync doesn't read .gitignore

### ISSUE THREAD

**Issue by samblam** [Labhk/BoltSync-Issues#5]
boltsync should read .gitignore, and not include said files to the push to Github. .env, etc.

**Comment by Labhk** [comment]
> boltsync should read .gitignore, and not include said files to the push to Github. .env, etc.

I added code to ignore .env file,node_modules, dist folder as of now.
I'll add the feature to read the .gitignore later when I get the time.

**Comment by samblam** [comment]
very cool. Thanks

**Comment by Labhk** [comment]
@samblam Added this feature too
Let me know if it works for you.
Thank you
