### ISSUE TITLE
Files marked in .gitignore are being committed

### ISSUE THREAD

**Issue by karthickshiva** [Labhk/BoltSync-Issues#6]
Files that are explicitly listed in the .gitignore file are still being tracked and committed to the Git repository. This behavior is unexpected and goes against the purpose of the .gitignore file, which is meant to prevent certain files and directories from being tracked by Git.

**Comment by Labhk** [comment]
I added code to ignore .env file,node_modules, dist folder as of now.
I'll add the feature to read the .gitignore later when I get the time.

**Comment by Labhk** [comment]
@karthickshiva  Added this Feature
Let me know if it works for you.
Thank you
