### ISSUE TITLE
error processing zip file: owner is not defined

### ISSUE THREAD

**Issue by torielstrom** [Labhk/BoltSync-Issues#8]
This no longer works. Everytime you upload the zip file... it just says "error processing zip file: owner is not defined"

I tested:

- Adjusting the owner of the zip file on my local computer.
- Clearing Cache
- Incognito
-Uninstalling and reinstalling

**Comment by Labhk** [comment]
Thank you for reporting, I made a slight change in code today, didn't know the zip upload had a problem.
fixed it.
Let me know if still get this issue. 
Happy Holidays

**Comment by Labhk** [comment]
fixed issue
