### ISSUE TITLE
Deleted files still appear after sync

### ISSUE THREAD

**Issue by dmenchaca** [Labhk/BoltSync-Issues#9]
If I deleted a file and upload the zip and I see "Found 0 changes". 

My expected result would be that BoltSync would detect that there was a deleted file and marge that change with the repo.

## Steps to reproduce this issue:
- Ask Bolt to delete any file.
- Upload the zip using BoltSync.
- Click "Detect changes"
- You should see "Found 0 changes"

## Screenshot
<img width="1126" alt="Screenshot 2024-12-28 at 09 03 22" src="https://github.com/user-attachments/assets/79b53f97-f834-4c18-863f-4b7b61b76e3b" />

**Comment by Labhk** [comment]
oh yes! I over looked this part, I'll make the changes.

**Comment by dmenchaca** [comment]
@Labhk thanks for the fast reply.

I'll keep an eye on this issue for it's closed so I can resync.

Happy holidays!

**Comment by Labhk** [comment]
@dmenchaca  Added your suggestion and Ability to leave commit message and some other changes too.
Let me know if it works for you.
Thank you

**Comment by dmenchaca** [comment]
@Labhk thanks for the new change, its looking great.

One glitch I still notice is that per sync there is a separate commit for every changed file. 

My expected result is that each sync would create a single commit.

Here you can see this on my repo: https://github.com/dmenchaca/userbird/commits/main/

Do you experience the same behavior?

**Comment by Labhk** [comment]
@dmenchaca 
Yes I got this too, Fixed now
Now its all in one commit pushing changes.
Check it out

**Comment by dmenchaca** [comment]
@Labhk amazing, looking great.

Thanks a lot! 🙏

Feel free to mark this issue as resolved.

**Comment by Labhk** [comment]
Alright
